### PR TITLE
Verify Remote URL for Git Dependencies

### PR DESCRIPTION
**Pull request by steviegt6**
_See [FunkinCrew/funkinBounties#1](https://github.com/FunkinCrew/funkinBounties/issues/1) for additional context._

## The Problem

Switching URLs for Git dependencies but not switching refs will cause hmm to skip over validation if the refs are verifiable (working with forks in most contexts, dealing with branches of the same name, etc.).

## The Solution

Check the origin remote's URL and validate it against the URL used for cloning the repository. Shouldn't cause issues, but may require a tad bit more consideration for production. Works in the context of solving the aforementioned issue, though.

### CODE REVIEW

**Comment by andywhite37** [comment]
This looks good to me, thanks! I haven't done any haxe stuff for awhile, but I'll merge this and see if I can push out a new release to haxelib.

**Comment by steviegt6** [comment]
Awesome, thank you!

**Comment by steviegt6** [comment]
Any update on this, @andywhite37?

**Comment by ninjamuffin99** [comment]
looking forward to a haxelib release woohoo! 

can confirm that it works all good 🤝

**Comment by andywhite37** [comment]
Sorry all! I'll try to get this pushed out today sometime!

**Comment by steviegt6** [comment]
Thank you!

**Comment by andywhite37** [comment]
Sorry again, I've had a crazy couple days at work/home, but I promise I will get this out ASAP.

**Comment by andywhite37** [comment]
Ok, I pushed out version 3.0.0 to haxelib. I bumped up to v3 because I updated thx.core and utest dependencies along with this fix, to get it to build more easily.

I'm pretty far out of the `haxe` world, so please let me know if this new version works for you or not!

**Pull request merged**
