### PR TITLE
Add Windows platform support

### PR DESCRIPTION
**Pull request by elsassph**
Fixes issue #5
- added `hmm.cmd` script
- `hmm setup` copies `hmm.cmd` inside Haxe SDK directory, making it available globally
- `hmm remove` deletes `hmm.cmd` from the Haxe SDK
- logger ansi colouring is disabled on Windows (although some ansi capable consoles may exist, it's difficult to detect)
- fixed `haxelib` version parser

### CODE REVIEW

**Comment by andywhite37** [comment]
Awesome, thank you for this PR!

**Comment by andywhite37** [comment]
I submitted your change to lib.haxe.org as version 2.0.1.  Let me know if everything is working okay.

**Comment by jonasmalacofilho** [comment]
Reporting a small issue found by a colegue (@craice)...

We found a small problem related to missing path quoting: `haxelib run hmm setup` tries to execute `copy /Y C:\HaxeToolkit\haxe\lib\hmm\2,0,1\hmm.cmd C:\HaxeToolkit\haxe\hmm.cmd`, but Windows gets tripped up by the commas and the command fails with `The system cannot find the file specified`.

<details>
<summary>Version information</summary>

```
haxe -version: 3.4.1 (git build development @ 6899468)
neko -version: 2.1.0
on Windows 10 Pro Version 1607 OS Build 14393.1198
```
</details>

**Comment by andywhite37** [comment]
Ok, I created an issue for this: #14

**Pull request merged**
