### PR TITLE
Introducing "hmm lock"

### PR DESCRIPTION
**Pull request by elsassph**
```
> hmm help lock

    lock - update libraries versions or refs in hmm.json.

        usage: hmm lock [<lib1> [... <libn>]]

        arguments: zero or more library names

        - haxelib library: the current version is written
        - git/hg library: the current hash ref is written
        - dev library: nothing happens

        example:

        hmm lock
        - locks all libraries

        hmm lock thx.core
        hmm lock thx.core mithril
        - locks specific libraries only

> hmm lock

Lock react to version 1.2.0
1 out of 4 library version has been updated
```

Implements issue #17

### CODE REVIEW

**Comment by elsassph** [comment]
Note I don't have Mercurial to verify if the ref is correctly extracted - please try :)

**Comment by andywhite37** [comment]
Looks good!  Thanks for your contributions

**Comment by andywhite37** [comment]
Released in 2.1.0

**Comment by elsassph** [comment]
You did try with mercurial, did you?

**Comment by andywhite37** [comment]
I haven't really tried things with mercurial in general.  I try to support it as much as I can, and as much as haxelib allows, but I haven't been too worried about it.

**Comment by elsassph** [comment]
Ok we'll see if anyone raise an issue :D
For git to tries to get the tag - works for you?

**Comment by andywhite37** [comment]
Yeah, I liked the git solution of trying to find a tag, then falling back to the commit.  Nicely done.

Yeah, my unofficial/undocumented stance on mercurial is to wait until someone complains, mostly because I've never used mercurial myself.

**Pull request merged**
